openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger API
externalDocs:
  description: View the raw OpenAPI Specification in JSON format
  url: /swagger.json
components:
  schemas:
    Customer:
      type: object
      properties:
        object:
          type: string
          enum:
            - customer
          default: customer
        id:
          type: string
        name:
          type: string
          minLength: 3
          maxLength: 200
        metadata:
          type: object
          additionalProperties:
            type: string
            minLength: 1
            maxLength: 500
        createdAt:
          type: string
        updatedAt:
          type: string
      required:
        - id
        - name
        - metadata
        - createdAt
        - updatedAt
      additionalProperties: false
  parameters: {}
paths:
  /status:
    get:
      tags:
        - Status Check
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  responseObject:
                    nullable: true
                  statusCode:
                    type: number
                required:
                  - success
                  - message
                  - statusCode
  /customers:
    get:
      tags:
        - Customer
      parameters:
        - schema:
            type: object
            properties:
              limit:
                type: string
              cursor:
                type: string
              filter:
                type: object
                properties:
                  name:
                    type: string
                  metadata:
                    type: object
                    additionalProperties:
                      type: string
                additionalProperties: false
            additionalProperties: false
          required: false
          name: query
          in: query
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  responseObject:
                    type: array
                    items:
                      type: object
                      properties:
                        object:
                          type: string
                          enum:
                            - customer
                          default: customer
                        id:
                          type: string
                        name:
                          type: string
                          minLength: 3
                          maxLength: 200
                        metadata:
                          type: object
                          additionalProperties:
                            type: string
                            minLength: 1
                            maxLength: 500
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                      required:
                        - id
                        - name
                        - metadata
                        - createdAt
                        - updatedAt
                      additionalProperties: false
                  statusCode:
                    type: number
                required:
                  - success
                  - message
                  - statusCode
    post:
      tags:
        - Customer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Customer created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  responseObject:
                    type: object
                    properties:
                      object:
                        type: string
                        enum:
                          - customer
                        default: customer
                      id:
                        type: string
                      name:
                        type: string
                        minLength: 3
                        maxLength: 200
                      metadata:
                        type: object
                        additionalProperties:
                          type: string
                          minLength: 1
                          maxLength: 500
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                    required:
                      - id
                      - name
                      - metadata
                      - createdAt
                      - updatedAt
                    additionalProperties: false
                  statusCode:
                    type: number
                required:
                  - success
                  - message
                  - statusCode
  /customers/{id}:
    get:
      tags:
        - Customer
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  responseObject:
                    type: object
                    properties:
                      object:
                        type: string
                        enum:
                          - customer
                        default: customer
                      id:
                        type: string
                      name:
                        type: string
                        minLength: 3
                        maxLength: 200
                      metadata:
                        type: object
                        additionalProperties:
                          type: string
                          minLength: 1
                          maxLength: 500
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                    required:
                      - id
                      - name
                      - metadata
                      - createdAt
                      - updatedAt
                    additionalProperties: false
                  statusCode:
                    type: number
                required:
                  - success
                  - message
                  - statusCode
